sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - openssl aes-256-cbc -K $encrypted_3eba8b62c709_key -iv $encrypted_3eba8b62c709_iv -in multi-k8s-228005-99db62f35707.json.enc -out multi-k8s-228005-99db62f35707.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file multi-k8s-228005-99db62f35707.json
  - gcloud config set project multi-k8s-228005
  - gcloud config set compute/zone us-central1-a
  - gcloud container clusters get-credentials multi-k8s --zone=us-central1-a
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t anoopagarwal/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run anoopagarwal/react-test npm test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
